// Package camera manages the mediamtx RTSP server and camera pipeline.
package camera

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"time"

	"github.com/zikeji/ManlyCam/apps/agent/internal/config"
)

// BuildMTXConfig generates a mediamtx YAML configuration for the rpiCamera source.
// It is a pure function with no side effects — testable without hardware.
//
// mediamtx owns the libcamera pipeline internally, keeping the camera active
// regardless of whether any RTSP client is connected. This eliminates the
// crash-on-disconnect bug of the previous rpicam-vid --listen approach.
//
// The generated config exposes:
//
//	rtsp://localhost:<rtsp_port>/cam   (frp stream tunnel → server)
//	http://127.0.0.1:<api_port>/       (frp api tunnel → server proxy for Story 3.6 controls)
func BuildMTXConfig(cfg config.StreamConfig) string {
	hflip := "false"
	if cfg.HFlip {
		hflip = "true"
	}
	vflip := "false"
	if cfg.VFlip {
		vflip = "true"
	}
	tuningLine := ""
	if cfg.TuningFile != "" {
		tuningLine = fmt.Sprintf("\n    rpiCameraTuningFile: %s", cfg.TuningFile)
	}
	return fmt.Sprintf(`# Generated by ManlyCam agent — do not edit manually
rtspAddress: ":%d"
api: yes
apiAddress: "127.0.0.1:%d"

paths:
  cam:
    source: rpiCamera
    rpiCameraWidth: %d
    rpiCameraHeight: %d
    rpiCameraFPS: %d
    rpiCameraHFlip: %s
    rpiCameraVFlip: %s%s
`, cfg.RTSPPort, cfg.APIPort, cfg.Width, cfg.Height, cfg.Framerate, hflip, vflip, tuningLine)
}

// Pipeline manages the mediamtx subprocess lifecycle.
type Pipeline struct{}

// Start writes a temp mediamtx config, launches mediamtx, and supervises it.
// On crash it restarts after a 2s delay (giving libcamera time to fully release
// the camera device). On context cancellation it stops mediamtx and returns
// ctx.Err().
//
// mediamtx spawns a helper process (mtxrpicam) that owns the camera device.
// If mediamtx is killed hard (SIGKILL), mtxrpicam can survive as an orphan and
// hold the camera open, preventing re-acquisition. To handle this:
//   - On startup: any stale mtxrpicam processes are killed before mediamtx starts.
//   - On graceful shutdown: the entire process group is sent SIGTERM so mediamtx
//     can propagate the signal to its children before exiting.
func (p *Pipeline) Start(ctx context.Context, cfg config.StreamConfig) error {
	if _, err := exec.LookPath("mediamtx"); err != nil {
		return fmt.Errorf("mediamtx binary not found on PATH: %w", err)
	}

	killStaleMtxrpicam()

	tmpFile, err := writeTempMTXConfig(cfg)
	if err != nil {
		return err
	}
	defer os.Remove(tmpFile)

	for {
		cmd := exec.CommandContext(ctx, "mediamtx", tmpFile)
		cmd.Stdout = os.Stderr // mediamtx logs to stdout; redirect to our stderr
		cmd.Stderr = os.Stderr

		// Put mediamtx in its own process group so we can signal the whole tree.
		cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

		// When the context is cancelled, SIGTERM the process group instead of
		// SIGKILLing only the mediamtx process. This gives mediamtx a chance to
		// terminate its mtxrpicam child, releasing the camera device cleanly.
		cmd.Cancel = func() error {
			if cmd.Process == nil {
				return nil
			}
			return syscall.Kill(-cmd.Process.Pid, syscall.SIGTERM)
		}

		if err := cmd.Run(); err != nil {
			if ctx.Err() != nil {
				return ctx.Err()
			}
			log.Printf("mediamtx crashed: %v; restarting in 2s", err)
			killStaleMtxrpicam()
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-time.After(2 * time.Second):
			}
			continue
		}
		// mediamtx exited cleanly (unexpected) — restart.
		if ctx.Err() != nil {
			return ctx.Err()
		}
		log.Printf("mediamtx exited cleanly; restarting")
	}
}

// killStaleMtxrpicam kills any mtxrpicam helper processes left behind by a
// previous mediamtx crash. These processes hold the camera device open and
// prevent re-acquisition until killed.
//
// mediamtx extracts mtxrpicam to /dev/shm/mediamtx-rpicamera-<random>/ at
// startup. The binary name is stable enough to match with pkill -f.
func killStaleMtxrpicam() {
	matches, _ := filepath.Glob("/dev/shm/mediamtx-rpicamera-*/mtxrpicam")
	if len(matches) == 0 {
		return
	}
	log.Printf("killing %d stale mtxrpicam process(es) before starting mediamtx", len(matches))
	if err := exec.Command("pkill", "-f", "mtxrpicam").Run(); err != nil {
		// pkill exits 1 when no processes matched — not a real error.
		log.Printf("pkill mtxrpicam: %v", err)
	}
	// Brief pause to let the camera device fully release before mediamtx starts.
	time.Sleep(500 * time.Millisecond)
}

func writeTempMTXConfig(cfg config.StreamConfig) (string, error) {
	f, err := os.CreateTemp("", "mediamtx-*.yml")
	if err != nil {
		return "", fmt.Errorf("creating temp mediamtx config: %w", err)
	}
	defer f.Close()
	if _, err := f.WriteString(BuildMTXConfig(cfg)); err != nil {
		os.Remove(f.Name())
		return "", fmt.Errorf("writing temp mediamtx config: %w", err)
	}
	return f.Name(), nil
}
