import { spawn, type ChildProcess } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { env } from '../env.js';
import { logger } from '../lib/logger.js';
import { wsHub } from './wsHub.js';
import type { StreamState } from '@manlycam/types';

// Generates a mediamtx YAML config that pulls RTSP from the Pi (via frp tunnel)
// and re-publishes it as WebRTC WHEP for browser consumption.
// All other protocols are disabled to minimise attack surface.
export function buildMTXConfig(): string {
  return (
    [
      '# Generated by ManlyCam server — do not edit manually',
      `rtspAddress: ":0"`,
      `rtmpAddress: ":0"`,
      `hlsAddress: ":0"`,
      `srtAddress: ":0"`,
      `webrtcAddress: ":${env.MTX_WEBRTC_PORT}"`,
      `apiAddress: "127.0.0.1:${env.MTX_API_PORT}"`,
      '',
      'paths:',
      '  cam:',
      `    source: rtsp://${env.FRP_HOST}:${env.FRP_RTSP_PORT}/cam`,
      '    sourceProtocol: tcp',
    ].join('\n') + '\n'
  );
}

export class StreamService {
  private adminToggle: 'live' | 'offline' = 'live';
  private piReachable = false;
  private stopped = false;
  private proc: ChildProcess | null = null;
  private configDir: string | null = null;

  getState(): StreamState {
    if (this.adminToggle === 'offline') return { state: 'explicit-offline' };
    if (this.piReachable) return { state: 'live' };
    return { state: 'unreachable', adminToggle: 'live' };
  }

  setAdminToggle(toggle: 'live' | 'offline'): void {
    this.adminToggle = toggle;
    this.broadcastState();
  }

  start(): void {
    this.supervisorLoop().catch((err) => {
      logger.error({ err }, 'mediamtx supervisor loop exited unexpectedly');
    });
    this.pollLoop().catch((err) => {
      logger.error({ err }, 'mediamtx poll loop exited unexpectedly');
    });
  }

  stop(): void {
    this.stopped = true;
    this.proc?.kill('SIGTERM');
    if (this.configDir) {
      rmSync(this.configDir, { recursive: true, force: true });
      this.configDir = null;
    }
  }

  private broadcastState(): void {
    wsHub.broadcast({ type: 'stream:state', payload: this.getState() });
  }

  private async supervisorLoop(): Promise<void> {
    // Create temp directory for mediamtx config. Cleanup is handled in stop() on graceful shutdown.
    // If supervisor loop exits unexpectedly, temp dir is left with identifiable prefix (manlycam-mtx-)
    // in /tmp, which will be auto-cleaned by the OS on reboot.
    this.configDir = mkdtempSync(join(tmpdir(), 'manlycam-mtx-'));
    const configPath = join(this.configDir, 'mediamtx.yml');
    writeFileSync(configPath, buildMTXConfig());

    const RETRY_DELAY_MS = 5000;
    while (!this.stopped) {
      if (this.adminToggle === 'offline') {
        await new Promise((r) => setTimeout(r, 2000));
        continue;
      }
      await this.runMediamtx(configPath);
      if (!this.stopped) {
        logger.info({ retryMs: RETRY_DELAY_MS }, 'mediamtx: retrying after delay');
        await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
      }
    }
  }

  private runMediamtx(configPath: string): Promise<void> {
    return new Promise((resolve) => {
      logger.info('mediamtx: spawning');
      const proc = spawn('mediamtx', [configPath], { stdio: ['ignore', 'pipe', 'pipe'] });
      this.proc = proc;

      proc.on('spawn', () => {
        logger.info('mediamtx: process started');
      });

      proc.on('error', (err) => {
        logger.error({ err }, 'mediamtx: failed to spawn (is mediamtx installed on PATH?)');
        this.proc = null;
        resolve();
      });

      proc.on('close', (code, signal) => {
        logger.warn({ code, signal }, 'mediamtx: process exited');
        if (this.piReachable) {
          this.piReachable = false;
          this.broadcastState();
        }
        this.proc = null;
        resolve();
      });
    });
  }

  private async pollLoop(): Promise<void> {
    // Allow mediamtx time to start before first poll
    await new Promise((r) => setTimeout(r, 3000));
    while (!this.stopped) {
      await this.pollMediamtxState();
      await new Promise((r) => setTimeout(r, 2000));
    }
  }

  async pollMediamtxState(): Promise<void> {
    try {
      const res = await fetch(`http://127.0.0.1:${env.MTX_API_PORT}/v3/paths/get/cam`);
      if (!res.ok) {
        this.updateReachable(false);
        return;
      }
      const data = (await res.json()) as { ready: boolean };
      this.updateReachable(data.ready === true);
    } catch {
      // mediamtx not yet running or restarting — treat as unreachable
      this.updateReachable(false);
    }
  }

  private updateReachable(reachable: boolean): void {
    if (reachable !== this.piReachable) {
      this.piReachable = reachable;
      logger.info({ piReachable: reachable }, 'stream: Pi reachability changed');
      this.broadcastState();
    }
  }
}

export const streamService = new StreamService();
